
version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/backend/app
    env_file:
      - 'backend/.env'
    ports:
      - "5555:5555"
