
version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - 'backend/.env'
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./backend/app:/backend/app
      - ./backend/tests:/backend/tests
    env_file:
      - 'backend/.env'
    ports:
      - "5555:5555"
